-- ─── V1 — Initial schema: transactions table ─────────────────────────────────
-- EN: Creates the core 'transactions' table and two supporting indexes.
--     Managed by Flyway; this file is versioned (V1__) and runs exactly once
--     per database. The 'validate' DDL-auto setting in JPA means Hibernate
--     confirms the schema matches the entity at every startup but never modifies it.
--
-- ES: Crea la tabla principal 'transactions' y dos índices de soporte.
--     Gestionada por Flyway; este archivo está versionado (V1__) y se ejecuta exactamente
--     una vez por base de datos. La configuración 'validate' de DDL-auto en JPA significa
--     que Hibernate confirma que el esquema coincide con la entidad en cada inicio pero
--     nunca lo modifica.

create table transactions (
    -- EN: Surrogate primary key. GENERATED BY DEFAULT AS IDENTITY lets the application
    --     provide an explicit id (useful in tests) while still auto-incrementing by default.
    -- ES: Clave primaria sustituta. GENERATED BY DEFAULT AS IDENTITY permite a la aplicación
    --     proporcionar un id explícito (útil en tests) mientras sigue auto-incrementando por defecto.
    id                      integer generated by default as identity primary key,

    -- EN: Transaction amount in Chilean pesos. The CHECK constraint enforces the business rule
    --     "no negative amounts" at the database level, providing an additional safety layer
    --     beyond the bean validation on TransactionRequest.
    -- ES: Monto de la transacción en pesos chilenos. La restricción CHECK hace cumplir la regla
    --     de negocio "sin montos negativos" a nivel de base de datos, proporcionando una capa
    --     de seguridad adicional más allá de la bean validation en TransactionRequest.
    amount_in_pesos         integer not null check (amount_in_pesos >= 0),

    -- EN: Merchant name exactly as stored (whitespace normalized, original casing).
    --     VARCHAR(160) matches the @Size(max=160) constraint in TransactionRequest.
    -- ES: Nombre del comercio exactamente como se almacenó (espacios normalizados, mayúsculas originales).
    --     VARCHAR(160) coincide con la restricción @Size(max=160) en TransactionRequest.
    merchant                varchar(160) not null,

    -- EN: Display name for the Tenpista with original casing.
    --     VARCHAR(120) matches the @Size(max=120) constraint in TransactionRequest.
    -- ES: Nombre visible del Tenpista con mayúsculas originales.
    --     VARCHAR(120) coincide con la restricción @Size(max=120) en TransactionRequest.
    customer_name           varchar(120) not null,

    -- EN: Lower-cased, single-space-normalized copy of customer_name.
    --     Used by the indexed equality lookup in TransactionRepository so that
    --     "Camila Torres", "CAMILA TORRES", and "  camila   torres  " all match.
    -- ES: Copia en minúsculas y con espacios normalizados de customer_name.
    --     Usada por la búsqueda de igualdad indexada en TransactionRepository para que
    --     "Camila Torres", "CAMILA TORRES" y "  camila   torres  " coincidan todas.
    customer_name_normalized varchar(120) not null,

    -- EN: UTC timestamp for the moment the transaction occurred.
    --     Stored without timezone offset (naive UTC); the JDBC layer handles conversion.
    -- ES: Timestamp UTC para el momento en que ocurrió la transacción.
    --     Almacenado sin offset de zona horaria (UTC naive); la capa JDBC maneja la conversión.
    transaction_date        timestamp not null
);

-- EN: Composite index supporting the default list query (ORDER BY transaction_date DESC, id DESC).
--     Covering both columns avoids a sort step — PostgreSQL can satisfy the ORDER BY directly
--     from the index scan.
-- ES: Índice compuesto que soporta la consulta de lista por defecto (ORDER BY transaction_date DESC, id DESC).
--     Cubrir ambas columnas evita un paso de ordenación — PostgreSQL puede satisfacer el ORDER BY
--     directamente desde el escaneo del índice.
create index idx_transactions_transaction_date
    on transactions (transaction_date desc, id desc);

-- EN: Single-column index supporting the customer name filter query and the quota count query.
--     Both 'findAllByCustomerNameNormalized...' and 'countByCustomerNameNormalized' hit this index.
-- ES: Índice de columna única que soporta la consulta de filtro por nombre de cliente y la consulta de conteo de cuota.
--     Tanto 'findAllByCustomerNameNormalized...' como 'countByCustomerNameNormalized' usan este índice.
create index idx_transactions_customer_name_normalized
    on transactions (customer_name_normalized);
