create table transactions (
    id integer generated by default as identity primary key,
    amount_in_pesos integer not null check (amount_in_pesos >= 0),
    merchant varchar(160) not null,
    customer_name varchar(120) not null,
    customer_name_normalized varchar(120) not null,
    transaction_date timestamp not null
);

create index idx_transactions_customer_name_normalized
    on transactions (customer_name_normalized);

create index idx_transactions_transaction_date
    on transactions (transaction_date desc, id desc);
