package com.tenpo.challenge.transaction;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

/**
 * EN: Immutable request DTO (Data Transfer Object) for creating or updating a transaction.
 *     Declared as a Java {@code record} to eliminate boilerplate: the constructor, accessors,
 *     {@code equals}, {@code hashCode}, and {@code toString} are all generated by the compiler.
 *
 *     Validation is applied via Jakarta Bean Validation annotations. Any violation causes
 *     Spring to reject the request with a 400 Bad Request response assembled by
 *     {@code GlobalExceptionHandler.handleValidation}.
 *
 *     Security note: {@code amountInPesos} is declared as {@code long} (not {@code int})
 *     to accept JSON numbers larger than Integer.MAX_VALUE without a parse error, then
 *     the {@code @Max} constraint rejects values that overflow int range before they reach
 *     the service. This design prevents a silent integer overflow that could result in a
 *     negative persisted amount.
 *
 * ES: DTO (Data Transfer Object) de solicitud inmutable para crear o actualizar una transacción.
 *     Declarado como {@code record} de Java para eliminar código repetitivo: el constructor,
 *     accesores, {@code equals}, {@code hashCode} y {@code toString} son todos generados por el compilador.
 *
 *     La validación se aplica via anotaciones Jakarta Bean Validation. Cualquier violación hace
 *     que Spring rechace la solicitud con una respuesta 400 Bad Request ensamblada por
 *     {@code GlobalExceptionHandler.handleValidation}.
 *
 *     Nota de seguridad: {@code amountInPesos} se declara como {@code long} (no {@code int})
 *     para aceptar números JSON más grandes que Integer.MAX_VALUE sin error de análisis, luego
 *     la restricción {@code @Max} rechaza valores que desbordan el rango int antes de llegar
 *     al servicio. Este diseño previene un desbordamiento de entero silencioso que podría resultar
 *     en un monto persistido negativo.
 *
 * Design — SOLID:
 *   SRP : Only describes the incoming payload contract; no business logic.
 */
@Schema(description = "Payload used to create or update a transaction.")
public record TransactionRequest(

        // EN: Amount in Chilean pesos. @PositiveOrZero allows zero (e.g. fee waivers).
        //     @Max caps the value at Integer.MAX_VALUE to prevent overflow when cast to int in the service.
        //     Using long in the DTO and int in the entity is intentional: it allows the validator
        //     to catch out-of-range values before any lossy integer conversion.
        // ES: Monto en pesos chilenos. @PositiveOrZero permite cero (ej. exenciones de comisión).
        //     @Max limita el valor a Integer.MAX_VALUE para prevenir desbordamiento al convertir a int en el servicio.
        //     Usar long en el DTO e int en la entidad es intencional: permite al validador
        //     detectar valores fuera de rango antes de cualquier conversión de entero con pérdida.
        @Schema(description = "Transaction amount in Chilean pesos.", example = "15000")
        @PositiveOrZero(message = "Transaction amount cannot be negative.")
        @Max(value = Integer.MAX_VALUE, message = "Transaction amount must stay within the supported integer range.")
        long amountInPesos,

        // EN: Name of the merchant or business category. Required and capped at 160 characters.
        //     @NotBlank rejects both null and whitespace-only strings.
        // ES: Nombre del comercio o categoría del giro. Requerido y limitado a 160 caracteres.
        //     @NotBlank rechaza tanto null como cadenas de solo espacios.
        @Schema(description = "Merchant or transaction category.", example = "Supermercado Lider")
        @NotBlank(message = "Merchant is required.")
        @Size(max = 160, message = "Merchant must be shorter than 160 characters.")
        String merchant,

        // EN: Display name for the Tenpista. Required and capped at 120 characters.
        //     The service will normalize whitespace before persisting.
        // ES: Nombre visible del Tenpista. Requerido y limitado a 120 caracteres.
        //     El servicio normalizará los espacios antes de persistir.
        @Schema(description = "Tenpista name.", example = "Camila Torres")
        @NotBlank(message = "Customer name is required.")
        @Size(max = 120, message = "Customer name must be shorter than 120 characters.")
        String customerName,

        // EN: Date and time when the transaction occurred.
        //     @NotNull ensures the field is present in the JSON body.
        //     @PastOrPresent enforces the challenge rule: no future-dated transactions.
        //     Jackson deserializes ISO-8601 strings (e.g. "2026-03-06T11:30:00") to LocalDateTime.
        // ES: Fecha y hora en que ocurrió la transacción.
        //     @NotNull asegura que el campo esté presente en el cuerpo JSON.
        //     @PastOrPresent hace cumplir la regla del challenge: sin transacciones con fecha futura.
        //     Jackson deserializa cadenas ISO-8601 (ej. "2026-03-06T11:30:00") a LocalDateTime.
        @Schema(description = "Transaction date and time.", example = "2026-03-07T11:30:00")
        @NotNull(message = "Transaction date is required.")
        @PastOrPresent(message = "Transaction date cannot be in the future.")
        LocalDateTime transactionDate
) {
}
