package com.tenpo.challenge.transaction;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import java.time.LocalDateTime;
import java.util.Locale;

/**
 * EN: JPA entity that maps to the {@code transactions} table in PostgreSQL.
 *     Each instance represents a single financial movement registered for a Tenpista.
 *     The {@code customerNameNormalized} column exists so that filtering and counting
 *     remain case-insensitive and whitespace-insensitive without runtime LOWER() calls.
 *
 * ES: Entidad JPA que mapea a la tabla {@code transactions} en PostgreSQL.
 *     Cada instancia representa un movimiento financiero registrado para un Tenpista.
 *     La columna {@code customerNameNormalized} existe para que los filtros y conteos
 *     sean insensibles a mayúsculas y espacios sin llamadas LOWER() en tiempo de ejecución.
 *
 * Design — SOLID:
 *   SRP: This class is only responsible for persistence mapping and normalization.
 *   OCP: Normalization logic is encapsulated in {@link #canonicalize(String)} so callers
 *        do not need to replicate it.
 */
@Entity
@Table(name = "transactions")
public class Transaction {

    // EN: Surrogate primary key generated by the database IDENTITY column (PostgreSQL serial).
    //     Read-only from the application side — no setter is exposed.
    // ES: Clave primaria sustituta generada por la columna IDENTITY de la BD (serial en PostgreSQL).
    //     Solo lectura desde la aplicación — no se expone setter.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    // EN: Transaction amount stored as an integer in Chilean pesos (CLP).
    //     The challenge specification requires integer; the DB CHECK constraint
    //     (amount_in_pesos >= 0) adds a database-level safeguard against corruption.
    // ES: Monto de la transacción almacenado como entero en pesos chilenos (CLP).
    //     La especificación del challenge requiere entero; la restricción CHECK en BD
    //     (amount_in_pesos >= 0) agrega una salvaguarda a nivel base de datos.
    @Column(name = "amount_in_pesos", nullable = false)
    private int amountInPesos;

    // EN: Name of the merchant or business category (e.g. "Supermercado Lider").
    //     Limited to 160 characters matching the VARCHAR(160) column definition.
    // ES: Nombre del comercio o categoría del giro (ej. "Supermercado Lider").
    //     Limitado a 160 caracteres que coinciden con la definición VARCHAR(160) de la columna.
    @Column(nullable = false, length = 160)
    private String merchant;

    // EN: Display name for the Tenpista as entered by the operator.
    //     This value is shown in the UI exactly as typed (preserving case and spacing).
    // ES: Nombre visible del Tenpista tal como lo ingresó el operador.
    //     Este valor se muestra en la UI exactamente como fue escrito (preservando mayúsculas y espacios).
    @Column(name = "customer_name", nullable = false, length = 120)
    private String customerName;

    // EN: Lowercase, single-space-normalized copy of customerName.
    //     Persisted separately so the indexed column (idx_transactions_customer_name_normalized)
    //     can support fast equality lookups without run-time string transformations.
    //     Automatically populated by the @PrePersist / @PreUpdate lifecycle hook.
    // ES: Copia en minúsculas y con espacios normalizados de customerName.
    //     Se persiste por separado para que la columna indexada (idx_transactions_customer_name_normalized)
    //     soporte búsquedas de igualdad rápidas sin transformaciones de cadena en tiempo de ejecución.
    //     Se llena automáticamente por el hook @PrePersist / @PreUpdate.
    @Column(name = "customer_name_normalized", nullable = false, length = 120)
    private String customerNameNormalized;

    // EN: Date and time when the transaction occurred, stored as UTC.
    //     Jackson serializes/deserializes this as ISO-8601 (e.g. "2026-03-07T11:30:00").
    //     The time zone offset is deliberately not persisted; the DB stores naive UTC timestamps.
    // ES: Fecha y hora en que ocurrió la transacción, almacenada en UTC.
    //     Jackson serializa/deserializa esto como ISO-8601 (ej. "2026-03-07T11:30:00").
    //     El offset de zona horaria no se persiste deliberadamente; la BD almacena timestamps UTC.
    @Column(name = "transaction_date", nullable = false)
    private LocalDateTime transactionDate;

    // ── Accessors ─────────────────────────────────────────────────────────────────────────

    // EN: Read-only accessor; the id is assigned by the database and must not be set externally.
    // ES: Accesor de solo lectura; el id es asignado por la BD y no debe establecerse externamente.
    public Integer getId() {
        return id;
    }

    public int getAmountInPesos() {
        return amountInPesos;
    }

    public void setAmountInPesos(int amountInPesos) {
        this.amountInPesos = amountInPesos;
    }

    public String getMerchant() {
        return merchant;
    }

    public void setMerchant(String merchant) {
        this.merchant = merchant;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerNameNormalized() {
        return customerNameNormalized;
    }

    public void setCustomerNameNormalized(String customerNameNormalized) {
        this.customerNameNormalized = customerNameNormalized;
    }

    public LocalDateTime getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDateTime transactionDate) {
        this.transactionDate = transactionDate;
    }

    // ── JPA Lifecycle Hook ────────────────────────────────────────────────────────────────

    /**
     * EN: Fires before every INSERT and every UPDATE so that {@code customerNameNormalized}
     *     is always derived from the current value of {@code customerName}.
     *     This guarantees that the search index is never stale, even if {@code customerName}
     *     changes through a PUT request.
     *
     * ES: Se ejecuta antes de cada INSERT y cada UPDATE para que {@code customerNameNormalized}
     *     siempre se derive del valor actual de {@code customerName}.
     *     Esto garantiza que el índice de búsqueda nunca esté desactualizado, incluso si
     *     {@code customerName} cambia a través de una solicitud PUT.
     */
    @PrePersist
    @PreUpdate
    void normalizeCustomerName() {
        // EN: Guard against null to avoid NPE during partial construction in tests.
        // ES: Guarda contra null para evitar NPE durante construcción parcial en tests.
        if (customerName != null) {
            customerNameNormalized = canonicalize(customerName);
        }
    }

    // ── Static Utility ────────────────────────────────────────────────────────────────────

    /**
     * EN: Produces the canonical form of a customer name: trim leading/trailing whitespace,
     *     collapse any sequence of internal whitespace to a single space, and convert to lower-case
     *     using the root locale (language-agnostic, consistent across JVMs).
     *     Exposed as {@code public static} so that the service layer can apply the same
     *     transformation before passing values to repository queries — ensuring that
     *     "Camila Torres", "  CAMILA  TORRES ", and "camila torres" all resolve to the
     *     same canonical key: {@code "camila torres"}.
     *
     * ES: Produce la forma canónica de un nombre de cliente: recortar espacios al inicio/final,
     *     colapsar cualquier secuencia de espacios internos a un solo espacio, y convertir a
     *     minúsculas usando el locale raíz (independiente del idioma, consistente entre JVMs).
     *     Expuesto como {@code public static} para que la capa de servicio aplique la misma
     *     transformación antes de pasar valores a las consultas del repositorio, garantizando
     *     que "Camila Torres", "  CAMILA  TORRES " y "camila torres" resuelvan al mismo
     *     clave canónica: {@code "camila torres"}.
     *
     * @param value the raw text value to canonicalize / el valor de texto sin procesar a canonizar
     * @return the canonical lower-cased, single-spaced form / la forma canónica en minúsculas y con un solo espacio
     */
    public static String canonicalize(String value) {
        return value.trim().replaceAll("\\s+", " ").toLowerCase(Locale.ROOT);
    }
}
